#
# Copyright (C) 2022 Jianhui Zhao <zhaojh329@gmail.com>
#
# This is free software, licensed under the MIT.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=WANset
APP_NAME:=wanset

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
